### ISSUE TITLE
ImportError: cannot import name 'dense_inference'

### ISSUE THREAD

**Issue by XYZ-916** [mbickel/DenseInferenceWrapper#16]
Thanks for sharing. When I set up the lib and import dense_interface, I got an error as follows:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home1/zhangyaxian16/zyx/CRF/DenseInferenceWrapper/denseinference/CRFProcessor.py", line 6, in <module>
    from denseinference.lib import dense_inference as di
ImportError: cannot import name 'dense_inference'

Any solutions? Thank you!

**Comment by LTYUnique** [comment]
Hi, I got the same problem. Did you resolve it?

**Comment by sdbonte** [comment]
Same here, any suggestions how this can be solved?

**Comment by soumickmj** [comment]
You need to first have to make the cpp package. But that was also resulting in error because obsolete packages been used. I have updated the codes and instructions in my forked version of this repo. Please go to : https://github.com/soumickmj/DenseInferenceWrapper
