### ISSUE TITLE
Error in 'make all' in the installation step

### ISSUE THREAD

**Issue by jayanth-culli** [mbickel/DenseInferenceWrapper#2]
pro = CRFProcessor.CRF3DProcessor() gvies error 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "denseinference/CRFProcessor.py", line 76, in __init__
    verbose)
TypeError: __init__() should return None, not 'NoneType'

**Comment by iabhi7** [comment]
Hi @cjayanth95  I guess its probably you are linking against the wrong Python library.
Make suitable changes in the make file to get rid of it. What version of Boost you have?
